name: Test and build project
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: Let's cache
        uses: actions/cache@v3
        with:
          path: mypath
          key: ${{ runner.os }}-mypath
      - name: run tests
        run: mvn test
  build_project:
    runs-on: ubuntu-latest
    needs: test_project
    steps:
      - name: get repository code
        uses: actions/checkout@v3
      - name: Let's cache
          uses: actions/cache@v3
          with:
            path: mypath
            key: ${{ runner.os }}-mypath
      - name: build project
        run: mvn package
  deploy_project_gibi:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - name: emulate deploy
        run: echo Deploy...